spring.application.name=BackendTingeso
server.port=8090

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/travel-realm

# Keycloak admin API configuration
keycloak.auth-server-url=http://localhost:8080
keycloak.realm=travel-realm
keycloak.admin.client-id=travel-backend-admin
keycloak.admin.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET}

# CORS frontend origin
app.frontend-origin=http://localhost:5173